### ISSUE TITLE
Vue.http.transforms is non-existent

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue-resource#59] opened 2015-10-20 11:55 UTC
The [docs](https://github.com/vuejs/vue-resource/blob/master/README.md) says we can use:
>Vue.http.transforms.request.push(function (options) {
>    return options;
>});

but searching through the source I found no occurrence of `transforms`..

**Comment by fnlctrl** [comment] 2015-10-20 12:02
Ok i found it's just not released, yet the README.md is updated...
So would you like to use a new branch, say `dev` for development ?

**Comment by kfirba** [comment] 2015-10-20 15:47
Seems like a duplicate of my issue: #58 

Anyways it doesn't seems like the maintainer is very active in this repo

**Comment by steffans** [comment] 2015-10-27 13:17
Currently we are on working the transform/interceptor feature. All the developement work is moved to a separate dev branch to avoid confusion about unreleased features.

**Closed by steffans** 2015-10-27 13:17 UTC
