### ISSUE TITLE
support lowercase response content-type

### ISSUE THREAD

**Issue by atian25** [vuejs/vue-resource#317] opened 2016-07-04 05:11 UTC
https://github.com/vuejs/vue-resource/blob/master/src/http/interceptor/body.js#L25

```

    next((response) => {

        var contentType = response.headers['Content-Type'];

        if (isString(contentType) && contentType.indexOf('application/json') === 0) {
```

**Comment by Nirazul** [comment] 2016-07-04 09:43
Came here to report the very same bug. I call that coincidence!

**Comment by juukie** [comment] 2016-07-04 10:55
I can confirm this bug. In Chrome, response won't be transformed to json because `response.headers['Content-Type']` = `null`.
`response.headers['content-type']` = `application/json`.

**Comment by Jigsaw5279** [comment] 2016-07-04 14:56
In the meantime, you can solve it like this:

https://github.com/vuejs/vue-resource/issues/314

**Comment by decademoon** [comment] 2016-07-11 11:01
Since HTTP header field names are case-insensitive, maybe it would be best to lowercase all the keys of Response.headers object?

**Comment by bruceman** [comment] 2016-07-28 10:40
We found this bug on latest Chrome, json data be resolved as string not object.

**Comment by LinusBorg** [comment] 2016-07-28 13:32
`response.json()`

**Comment by Nirazul** [comment] 2016-07-28 14:47
@LinusBorg 
Can you elaborate what you mean with your response? In terms of monkey-patching the issue, @Jigsaw5279 has already provided a more versatile and useful solution.

**Comment by LinusBorg** [comment] 2016-07-28 16:15
Ignore my comment, I had a misunderstanding.

**Comment by danpastori** [comment] 2016-08-11 01:05
Hey Guys,

I'm having the same issue. I wrote a simple interceptor to fix it for the time being if this helps anybody:

`Vue.http.interceptors.push((request, next ) => {
	next((response) => {
		if( 'Content-Type' in response.headers 
			&& response.headers['Content-Type'] == 'application/json' ){
			if( typeof response.data != 'object' ){
				response.data = JSON.parse( response.data );
			}
		}

		if( 'content-type' in response.headers
			&& response.headers['content-type'] == 'application/json' ){
			if( typeof response.data != 'object' ){
				response.data = JSON.parse( response.data );
			}
		}
	});
});`

**Comment by harrygr** [comment] 2016-08-15 22:16
This too has had me stumped for days! My scripts worked fine via plain Apache but broke when served via CloudFlare, and only on Chrome!

Fix would be much appreciated

**Comment by taylorotwell** [comment] 2016-08-17 22:50
Indeed this is broken.

**Comment by LinusBorg** [comment] 2016-08-17 23:05
It's already fixed in the `develop` branch with [this commit](https://github.com/vuejs/vue-resource/commit/627be7c9e54557b43e93e5ef6e45f3e5d27a1e99)

the next release will solve this.

**Comment by juukie** [comment] 2016-08-18 05:56
Thanks @LinusBorg!

**Comment by LinusBorg** [comment] 2016-08-18 06:56
@steffans fixed it, not me ;)

**Comment by juukie** [comment] 2016-08-18 07:27
@LinusBorg thanks for letting us know ;). @steffans thanks for fixing 👍

**Comment by xscence** [comment] 2016-08-19 13:51
Is this fixed ? Because i face same problem in vue-resource@0.9.3

**Comment by LinusBorg** [comment] 2016-08-19 13:58
Since there was no new release since my last comment: no, not in a public release (but yes, in the `develop` branch)

**Comment by uxweb** [comment] 2016-08-19 19:20
Hi, how do i install vue-resource develop branch using npm?

Thanks!

**Comment by LinusBorg** [comment] 2016-08-19 19:43
you can't. npm does not have the whole repsitory, only published versions.

you can however clone the repo as a subModule into a folder of your projects repo, and require it from there.

of course, do that at your own risk, the development branch may have bugs, or not even be working at all.

**Comment by Nirazul** [comment] 2016-08-20 19:39
@uxweb @LinusBorg 
In fact, you can! 
1. Just navigate to the commit you want, for example [this one](https://github.com/vuejs/vue-resource/commit/91fefa21faa88bc98271b43adbc23384ba46b93f)
2. Copy the url and replace `commit` with `tarball`
3. Install it normally via npm, for example `npm i -D https://github.com/vuejs/vue-resource/tarball/91fefa21faa88bc98271b43adbc23384ba46b93f`

Beware: This doesn't work for every module. Just for those that have no complicated npm publish setup and basically push everything from github to npm. But for `vue-resource` this works.

Beware 2: It's not recommended to use dev branches or random commits for anything more important than try-out or hobby projects. There's a big chance that such states have errors and/or flaws. After all, there are npm releases for a reason.

**Comment by uxweb** [comment] 2016-08-21 16:30
@LinusBorg Thanks!!,

I think is a better idea to include the interceptor proposed by @Jigsaw5279 👌

**Comment by alexkb** [comment] 2016-08-25 01:06
Interceptor worked great, thanks! 👍

**Closed** 2016-09-04 12:37 UTC
Labels: Bug

**Comment by devboxr** [comment] 2016-09-08 14:40
FIY, just saying
> Since HTTP header field names are case-insensitive, maybe it would be best to lowercase all the keys of Response.headers object? If this breaks for anyone, then their code is non-standard.

Is very reckless. There are frameworks out there (e.g. Code Igniter) that do not accept e.g. `authorization`. This will have indeed broken front-ends all around. Great. 👎
